### PR TITLE
Secure storage of Keystone credentials

### PR DESCRIPTION
**Pull request by dhague**

### CODE REVIEW

**Comment by rbak1** [comment]
Darren, you've changed this a few times, so just let me know when this merge request is stable and I'll take a look at it.

**Comment by dhague** [comment]
We just deployed it into QA today, so give us a few days and then I'll come back and OK it for review.

**Comment by dhague** [comment]
Hi Ryan - I'm happy this is stable now, so feel free to merge.

**Comment by dhague** [comment]
OK, good to go now.

**Comment by rbak1** [comment]
Darren, can you get this cleaned up so it doesn't change so many files?  We're still hoping to get this merged upstream at some point and we'd like to avoid a large change set.

**Pull request closed without merging**
